---
version: 1.0.{build}

branches:
  only:
    - master

image: Windows Server 2016

platform: x64

shallow_clone: true

install:
  - ps: ./prepare.ps1
  - ps: ./out/minishift.exe start --vm-driver hyperv

